service: helloworld-typescript

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 512 # optional, default is 1024, will be inherited by all functions
  timeout: 10 # optional, in seconds, default is 6
  httpApi:
    cors: true

params:
  dev:
    webscrape_page: "https://github.com/pittcsc/Summer2023-Internships"

functions:
  helloWorldFunction: 
    handler: index.handler
    name: hello-world-typescript # optional, Deployed Lambda name
    events:
      - httpApi:
          path: /parse
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
    serverless-offline:
        httpPort: 4000
        websocketPort: 4001
        lambdaPort: 4002